### PR TITLE
Update FLAnimatedImage.m

### PR DESCRIPTION
**Pull request by Cool-Tech**
Set the loop count to one less than the number of times you want the animation to run. An animation with --no-loopcount will show every frame once; --loopcount=1 will loop once, thus showing every frame twice; and so forth. Note that --loopcount=0 is equivalent to --loopcount=forever, not --no-loopcount.

### CODE REVIEW

**Comment by timonus** [comment]
Wow, this is a great find! I left a couple minor stylistic comments, if you address those I think we can merge this.

**Comment by timonus** [comment]
Awesome, thanks!

**Comment by timonus** [comment]
The gifsicle reference included in this PR is to a tool, but it would be good to include a reference describing this behavior somewhere in the actual GIF spec. I'm a bit uneasy about merging this then having it cause incorrect behavior when compared with a browser.

Could also include some reference GIFs in the comments that are supposed to loop:
- Forever
- Once
- A finite number of times
To test with.

**Comment by jfschedler** [comment]
My reading of the GIF89a spec says that images are rendered once by default, but it does not explicitly come right out an say it.  Other references, seem to back up the "run once" behavior as the default.

http://giflib.sourceforge.net/whatsinagif/animation_and_transparency.html says

> Next we encounter an application extension block. This is this block that causes our animation to repeat rather than play once and stop. 

And http://www.fileformat.info/format/gif/egff.htm

> The design of GIF87a only allowed the display of images one at a time in a "slide show" fashion. Through the interpretation and use of Control Extension data, GIF89a allows both textual and bitmap-based graphical data to be displayed, overlaid, and deleted as in an animated multimedia presentation.

GIF intended to loop once and does not have the NETSCAPE 2.0 block
mic_drop_loop_once

GIF intended to loop forever and does have the NETSCAPE 2.0 block
glass_loop_forever

I do not have an example of a GIF with a NETSCAPE 2.0 block with a loop count > 0.  (i.e. 1, 2, 3..), but hopefully the two provide will suffice.

Let me know if I can provide more info.  I'm not clear on the loopCount += 1 in the pull request.  It doesn't seem required, but I don't have a GIF with a loop count of 1 to use for a test.  I can try to make one.

**Comment by jfschedler** [comment]
Update to my comment above:

Example GIF intended to loop forever and has a NETSCAPE 2.0 block with loopCount = 0.
glass_loop_forever

Example GIF with NETSCAPE 2.0 block with loopCount = 1.  Note that the animation does run twice in a browser. (Perhaps a better name for the block field would have been repeatCount).

So this pull request looks legit to me and I hope the supplied answers to your questions can move it to acceptance.

**Comment by raphaelschaad** [comment]
(Merging this would also resolve #102)

**Comment by raphaelschaad** [comment]
I had a look and [left a detailed comment here](https://github.com/Flipboard/FLAnimatedImage/pull/198#issuecomment-787458172). Thanks for providing the example GIFs! I don't see a difference between Chrome/Safari and FLAnimatedImage.

**Pull request closed without merging**
