### PR TITLE
Enhanced initialization for FLAnimatedImage & FLAnimatedImageView

### PR DESCRIPTION
**Pull request by kdubb**
Overall it allows more efficient, and easier, loading of GIF or still images and loading them into an animated image view.

### CODE REVIEW

**Comment by timonus** [comment]
Much of this functionality could be easily implemented outside of FLAnimatedImage, and building as a framework has been working since 1.0.10. I'm going to close this PR.

**Comment by kdubb** [comment]
The framework parts weren't supposed to be in here. My mistake for not using a proper branch for the PR.  The init methods, although yes they can be implemented outside (as most things can), are fairly useful for using the library. Would you consider it if I commit without the framework commit?

**Comment by timonus** [comment]
I don't think the changes are necessary.

**Comment by kdubb** [comment]
Weird considering it implements something that has been noted in the code as basically a TODO.
https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L196

Necessary? no...  convenient? yes

**Comment by kdubb** [comment]
@timonus By the way... you cannot initialize an FLAnimatedImage from a CGImageSource without these changes. So, actually, no you cannot really implement this outside.  In our code we carry around CGImageSource's in a few different places.  I suppose you're suggesting I just turn those into NSData only to have FLAnimatedImage turn them back into a CGImageSource? I don't see the downsides of this code as it only expands the usefulness of the class and ensures there is no needless transcoding between CGImageSource and NSData.

**Comment by timonus** [comment]
Ah, yes, you're right. I've wanted to have an initializer that allows you to pass in an image source, I'll pull your changes that add that functionality out of this diff.

**Pull request closed without merging**
