### PR TITLE
Facebook patches for FLAnimatedImage

### PR DESCRIPTION
**Pull request by grp**
A few months ago, I saw a tweet that Ryan Olson [noticed](https://twitter.com/ryanolsonk/status/601429987795673088) that FLAnimatedImage was used in the Facebook apps. I've been working off-and-on since then to clean up the refactor and WebP support we'd done to contribute upstream, and it's finally ready now.

Since the version used in the Facebook app was branched almost a year ago, it was a little tricky to rebase onto master. I was only able to make it reasonable by rewriting the history, so this pull request has just two (relatively large) patches: one to make the image format support more pluggable, and one to add WebP support.

For both the patches, I decided to go with a multiple-target approach using subspec's rather than require pulling in libwebp for all uses of FLAnimatedImage. It's a little more complex, but it's closer to how we have it set up internally at Facebook and is more flexible for users.

Let me know if you have any questions. Most of the changes here were by @benhiller, I just cleaned them up for upstreaming, but we should both be able to answer questions on the approach or the code.

:rocket:

### CODE REVIEW

**Comment by lxcid** [comment]
Wow!

**Comment by tijoinc** [comment]
:wink:

**Comment by kean** [comment]
:octocat:

**Comment by timonus** [comment]
Hey there @grp and @benhiller, I'm working on reviewing this and I've run into a snag, looking for some help.

I've downloaded libwebp from [here](https://github.com/webmproject/libwebp/) and added it to the root level of the project, but I'm getting build errors when trying to run the sample project.

screen shot 2015-11-24 at 9 09 47 am

Also, I'm seeing a set of warnings about libwebp being built for iOS 9.1 but the FLAnimatedImage sample project being build for iOS 7, which we still support.

screen shot 2015-11-24 at 9 12 24 am


It looks like this patch might refer to an older version of libwebp, can you guys help? Thanks!

**Comment by timonus** [comment]
I would love to merge this, but it and master have diverged quite a bit and it is effectively a rewrite of much of the core of FLAnimatedImage. I'm going to close it, but I wanted to thank you for your contributions. I'll direct people in need of WebP support to your fork.

**Comment by PhilCai1993** [comment]
You saved me!

**Comment by crespoxiao** [comment]
@PhilCai1993  now you can use BDImageView for animate webp 😀

**Comment by fahad01000** [comment]
جميل

**Pull request closed without merging**
