### PR TITLE
Swift port of FLAnimatedImage with updated demo

### PR DESCRIPTION
**Pull request by dkasper**
This is a straightforward port of FLAnimatedImage to Swift, re: https://github.com/Flipboard/FLAnimatedImage/issues/14.

** Requires Xcode 6.1 or higher to compile **

The main classes are AnimatedGif and AnimatedGifView (same idea as FLAnimatedImage and FLAnimatedImageView). I added an additional screen and did a little bit of refactoring to the demo project to allow you to run either the Objective-C version or the new Swift version, which turns out to be a pretty good test to make sure they are as close to interchangeable as possible. We are using this in production on the Weebly iPad app and it is at a pretty stable point now.

The main issue is what to do since some people may not want to add Swift code to their codebase, and it also won't work with cocoapods yet. Some projects such as Masonry/Snappy, AFNetworking/AlamoFire are basically breaking the swift port into a separate library so that would also be an option, but since this is a port of the work here I wanted to put it up for discussion to see what you all think.

- @dkasper, props @ketzusaka and @jberkman for code review

### CODE REVIEW

**Comment by timonus** [comment]
I think we're going to pass on merging this for the time being for a few reasons:

- The version of Swift that this pull request migrates us to is now outdated, merging would cause it to not compile in the current version of Xcode.
- In general, Apple has said they're going to make significant changes to Swift over time. That means that by converting FLAnimatedImage to Swift we'll have to have many maintenance updates and more and more PRs will conflict over time.
- People developing apps in Objective-C who are sensitive about the size of their apps will have to include the Swift compatibility shim to adopt this library if it's migrated to Swift, which will increase their app size.
- FLAnimatedImage is usable from within Swift already because Swift and Objective-C are interoperable.
- Maintaining both an Objective-C and Swift version of FLAnimatedImage will be challenging, and the two may drift over time.

This will serve as a great reference if we do ever decide to port FLAnimatedImage to Swift, thank you for the pull request!

**Comment by dkasper** [comment]
@timonus No worries, solid reasoning. The benefits of the swift version are pretty small so I agree the maintenance is not worth it at this point.

**Comment by timonus** [comment]
Thanks!

**Comment by khaledmtaha** [comment]
@timonus I went ahead and ported it to Swift 2.0 as seen here on my [XAnimatedImage](https://github.com/khaledmtaha/XAnimatedImage). Had I seen this it would've saved me a lot of effort. :+1:

**Comment by timonus** [comment]
Oh nice! That's awesome!

**Pull request closed without merging**
