### PR TITLE
Optimal displayLink frame interval

### PR DESCRIPTION
**Pull request by ejensen**
Calculates  an optimal frame interval by calculating the greatest common divisor of frame durations.
This reduces the number of times `displayDidRefresh:` is executed when no image changes are need.

### CODE REVIEW

**Comment by timonus** [comment]
Nice

**Comment by ejensen** [comment]
Commit 347b4f6 `extern`'d  `kDelayTimeIntervalMinimum` and added more comments covering the `.frameInterval` calculation method.

**Comment by timonus** [comment]
I'd like to merge this change soon, but I'm seeing a discrepancy in performance. Here's a video comparing Chrome's GIF rendering with FLAnimatedImage's with your changes.

https://www.dropbox.com/s/6fwseyedezszcfs/after%20copy-12-11-2015-48775.mov?dl=0

You can see it's playing much slower. Here's the same comparison with the current version of FLAnimatedImage.

https://www.dropbox.com/s/1zcr9ds7ojz42d2/before%20copy-12-11-2015-49078.mov?dl=0

You can see there's quite a different. Any thoughts on why and how it might be resolved? This can't be merged unless we get the same playback performance out of it.

**Comment by ejensen** [comment]
The speed descrepency was introduced when I [merged the changed from `master`.](https://github.com/ejensen/FLAnimatedImage/commit/c8cc34b472e337d46ce11436e916c1183b30cb70)
I'll go through the changes to see what's going on.

**Comment by timonus** [comment]
Thank you.

**Comment by ejensen** [comment]
`kDelayTimeIntervalMinimum` lost a decimal when converting it to an extern :confounded:.  Commit 49263ee corrects it.

**Comment by timonus** [comment]
Ha, good catch!

**Comment by timonus** [comment]
Perfecto https://www.dropbox.com/s/0ejwgdq6yq6relx/nice%20copy-12-11-2015-55672.mov?dl=0

**Comment by timonus** [comment]
Alrighty, just merged this as 6cd714cf70e64181a59559f3848a35d39c3af086. I squashed it all into a single concise commit. Thanks for your contribution!

**Pull request closed without merging**
