### PR TITLE
Added SwiftPM support

### PR DESCRIPTION
**Pull request by YetAnotherRzmn**
#228

### CODE REVIEW

**Comment by Dimillian** [comment]
Will it be merged?

**Comment by YetAnotherRzmn** [comment]
I don't have permission to merge it

**Comment by cassianodialpad** [comment]
+1!
@thejohnlima @xav42mac Are you guys able to merge this?

**Comment by thejohnlima** [comment]
> +1!
> @thejohnlima @xav42mac Are you guys able to merge this?

Sorry, I don't have permission to merge it

**Comment by raphaelschaad** [comment]
This seems like a reasonable change. Happy to merge it but haven't tested it. /cc @matrush who's more cued in.

**Comment by cassianodialpad** [comment]
@raphaelschaad I have tested it here with master, it worked fine! (but it will work only for newer tagged versions, not for the current ones)

**Comment by raphaelschaad** [comment]
Released 1.0.15 https://github.com/Flipboard/FLAnimatedImage/issues/216 -- hope that all works out.

**Comment by fabiorodella** [comment]
This doesn't seem to work for me. I added the dependency on the 1.0.15 version to my iOS app through Xcode 12.4, but I get compilation errors:

```
In file included from /Users/fabiorodella/Library/Developer/Xcode/DerivedData/App-fhmsycgnuovdahdxceocnadvqhur/SourcePackages/checkouts/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.m:11:
/Users/fabiorodella/Library/Developer/Xcode/DerivedData/App-fhmsycgnuovdahdxceocnadvqhur/SourcePackages/checkouts/FLAnimatedImage/FLAnimatedImage/include/FLAnimatedImage.h:13:9: fatal error: 'FLAnimatedImage/FLAnimatedImageView.h' file not found
#import <FLAnimatedImage/FLAnimatedImageView.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Are there any other manual configuration steps necessary?

**Comment by fabiorodella** [comment]
FWIW, using the fork [for this PR](https://github.com/Flipboard/FLAnimatedImage/pull/243) (which the author closed) does work for me

**Comment by delvinwidjaja** [comment]
Hi, I tried forking the PR that you mentioned and still got the same error. Is there any workaround?

**Comment by fabiorodella** [comment]
The only thing I did was remove the FLAnimatedImage package dependency in Xcode and then add it again pointing to the `master` branch of https://github.com/Legoless/FLAnimatedImage, ran a clean and build and it worked.

**Pull request merged**
