### PR TITLE
Add Carthage support

### LINKED ISSUE #93: Carthage Does Not Build
adding the following to my Cartfile per the README.md

> If using Carthage, add following line into your Carfile

```
github "Flipboard/FLAnimatedImage"
```

results in the following:

```
*** Fetching FLAnimatedImage
*** Checking out FLAnimatedImage at "1.0.8"
*** xcodebuild output can be found in /var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/carthage-xcodebuild.ZtLzBd.log
Project "FLAnimatedImageDemo.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Flipboard/FLAnimatedImage/issues/new
```

### PR DESCRIPTION
**Pull request by kean**
Fixes #93

Changes:
- Add FLAnimatedImage.xcworkspace; Remove .xcworkspace from gitignore
- Move FLAnimatedImage/ to the root folder, update podspec accordingly
- Change framework and demo projects deployment target to iOS 8.0+
- Update framework and demo projects to recommended settings
- FLAnimatedImage added to demo project [by linking a static library](http://stackoverflow.com/questions/9726000/xcode-4-2-and-using-a-static-library-causing-problems/9726445#9726445)

### CODE REVIEW

**Comment by bpillon** [comment]
Is this possible to merge this ?

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [FLAnimatedImage] Add Carthage support (#95)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by timonus** [comment]
> Change framework and demo projects deployment target to iOS 8.0+

Wondering why you did this. I'll likely merge anyways, but doesn't seem necessary to support Carthage. Is it?

**Comment by timonus** [comment]
Thanks for this PR! Just merged at 1a6960acc3039a38496ad470edc774def0f15700.

**Comment by kean** [comment]
> Wondering why you did this. I'll likely merge anyways, but doesn't seem necessary to support Carthage. Is it?

Demo now links to FLAnimatedImage.framework (questionable change) and frameworks are only available on iOS 8 or later.

**Comment by kean** [comment]
I also just spotted that instead of importing headers from the linked framework (`#import <FLAnimatedImage/FLAnimatedImage.h>`) they are imported directly from "User Header Search Paths", which isn't nice.

**Comment by timonus** [comment]
Will update. Also noticed that if you're using Cocoa Lumberjack Logger that linking with the built library doesn't work because a header references non-modular headers. Filed an issue for that here https://github.com/Flipboard/FLAnimatedImage/issues/107.

**Comment by timonus** [comment]
@kean planning on having [this](fb4639eb4cf9353abae289f28ff53d85218c687b) in a PR sometime to address your feedback.

**Pull request closed without merging**
