### PR TITLE
Fix issue causing crashes when going through certain initializers.

### PR DESCRIPTION
**Pull request by timonus**
Identified in https://github.com/Flipboard/FLAnimatedImage/pull/128.

### CODE REVIEW

**Comment by timonus** [comment]
@jeffweitzel please review, thanks!

**Comment by timonus** [comment]
cc @kimar.

**Comment by kimar** [comment]
@timonus awesome, LGTM. Thank you!

**Comment by jeffweitzel** [comment]
+1

**Comment by timonus** [comment]
@kimar pushed to master, will likely put out a release with it tomorrow.

**Comment by kimar** [comment]
@timonus good stuff, really appreciate it. Thanks a bunch! 🎉

**Pull request merged**
