### PR TITLE
MobileCoreServices has been renamed. Use CoreServices instead.

### PR DESCRIPTION
**Pull request by smolskyaleksey**

### CODE REVIEW

**Comment by raphaelschaad** [comment]
@smolskyaleksey There seems to be a stray change in `FLAnimatedImage/FLAnimatedImageView.m` that isn't part of this PR?

**Comment by raphaelschaad** [comment]
@smolskyaleksey wouldn't [this commit](https://github.com/Flipboard/FLAnimatedImage/commit/b9db5565c6d7cd49ae41d011afa0794b359ca506) address the issue?

**Comment by smolskyaleksey** [comment]
Hi, you also shouldn't forget about import in .m file

**Comment by raphaelschaad** [comment]
I don't seem to get a warning from Xcode, though?

**Comment by smolskyaleksey** [comment]
I found this warning in the jenkins logs

**Pull request closed without merging**
