### PR TITLE
Changed property from NSString to NSRunLoop.

### PR DESCRIPTION
**Pull request by Elland**
This should render the module compatible with Swift3.0, as well as improving the Objc type checking.

😊

### CODE REVIEW

**Comment by 3lvis** [comment]
Any chance to get this merged?

**Comment by Elland** [comment]
@3lvis do we have to @ someone or a group? 🤔

**Comment by matrush** [comment]
If we can keep the `copy` instead of `strong`, I can merge this one.
If you look at the APIs in `NSRunloop.h`, it also uses `copy` instead
```
@property (nullable, readonly, copy) NSRunLoopMode currentMode;
```

**Comment by raphaelschaad** [comment]
Addressed in https://github.com/Flipboard/FLAnimatedImage/commit/7d5aa8bff7748d63987c7b56fd33fe28c14fcbd2

**Comment by Elland** [comment]
@raphaelschaad better later than never? :)

**Comment by raphaelschaad** [comment]
Yeah, looks like you never made the change that @matrush requested, so I stepped up on a quiet Sunday afternoon ;)

**Pull request closed without merging**
